### ISSUE TITLE
UI not rendered correctly

### ISSUE THREAD

**Issue by hrjonashansen** [JPEWdev/icecream-sundae#3]
The UI I see does not match the animated UI GIF.
I'm Using Ubuntu 18.04.1 LTS

![screenshot from 2019-02-06 09-42-10](https://user-images.githubusercontent.com/1670582/52330009-89abaf80-29f4-11e9-89fd-af1f23e0029b.png)

**Comment by JoshuaWatt** [comment]
It looks like one of your servers is reporting 64 maximum jobs and the job graph is pushing all the other columns way out... the UI should probably handle this better; maybe limiting the graph to some fixed number of columns?

**Comment by hrjonashansen** [comment]
I see, that makes sense. Perhaps a form of scaling for the "offending" server is in order, as opposed to just "cutting it" at some limit.

**Comment by medwards** [comment]
While I'm hacking at this: Do we care that the total jobs graph line wraps?

**Comment by hrjonashansen** [comment]
I cared enough to add such a change in my crude implementation. As a reference, I have attached said implementation.

[draw.zip](https://github.com/JPEWdev/icecream-sundae/files/2894138/draw.zip)

**Comment by JPEWdev** [comment]
> While I'm hacking at this: Do we care that the total jobs graph line wraps?

I think that makes sense. AFAIK, it doesn't cause rendering issues when it wraps, but it would probably look nicer if it scaled.

**Comment by JPEWdev** [comment]
Closed via cf889c148a83b3c9d714f9ed1e28856fa19d8cb3
